# development:
  # adapter: postgresql
  # encoding: utf8
  # reconnect: false
  # database: redpoint_commerce_dev
  # pool: 200
  # host: localhost
  # username: postgres
  # password: password

 development:
  adapter: postgresql
  encoding: unicode
  database: commerce
  pool: 5
  username: postgres
  password: postgres

test:
  adapter: postgresql
  encoding: unicode
  database: commerce
  pool: 5
  username: postgres
  password: postgres
