development:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: redpoint_commerce_dev
  pool: 200
  host: localhost
  username: postgres
  password: password

test:
  adapter: postgresql
  encoding: utf8
  reconnect: false
  database: redpoint_commerce_test
  pool: 200
  host: localhost
  username: postgres
  password: password
