production:
  adapter: postgresql
  encoding: unicode
  database: phsqcommerece1
  pool: 10
  username: phsqcommerece1
  password: phsqcommerece1
  host: phsqcommerece1.c3t8ly8irobc.us-east-1.rds.amazonaws.com
  # port: 5432
  # socket: /tmp/postgresql.sock