production:
  adapter: postgresql
  encoding: unicode
  database: phsqcommerece
  pool: 10
  username: phsqcommerece
  password: phsqcommerece
  host: phsqcommerece.c3t8ly8irobc.us-east-1.rds.amazonaws.com
  # port: 5432
  # socket: /tmp/postgresql.sock