production:
  access_key: 'your_access_key'
  access_secret: 'your_secret_key'
  bucket: 'your_s3_bucket'
  url: 'url_strategy'

development:
  access_key: 'your_access_key'
  access_secret: 'your_secret_key'
  bucket: 'your_s3_bucket'
  url: 'url_strategy'