production:
  access_key: 'AKIAJJGUHCUAKNL2LYAQ'
  access_secret: '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'
  bucket: 'redpoint-commerce'
 

development:
  access_key: 'AKIAJJGUHCUAKNL2LYAQ'
  access_secret: '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'
  bucket: 'redpoint-commerce'
